spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/explore_game
spring.datasource.username=gameuser
spring.datasource.password=gamepass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true